// <auto-generated />
namespace CourseWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AllModels_Validation_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllModels_Validation_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202111172334329_AllModels_Validation_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
