// <auto-generated />
namespace CourseWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Orders_AddedFKWaiter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Orders_AddedFKWaiter));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171234475_Orders_AddedFKWaiter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
