// <auto-generated />
namespace CourseWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MenuID_VariableType_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuID_VariableType_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171325039_MenuID_VariableType_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
