// <auto-generated />
namespace CourseWork1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Orders_AddedFKMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Orders_AddedFKMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "202111171150341_Orders_AddedFKMenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
